[package]
name = "gloomscript"
version = "0.1.0"
edition = "2018"

[dependencies]
hashbrown = "0.11"
clap = "3.0.13"
cranelift = "0.80.0"
cranelift-module = "0.80.0"
cranelift-jit = "0.80.0"
thiserror = "1.0.30"